language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/2.3
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper